# -*- coding: utf-8 -*-
"""indian_pines_svm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XDH7M87_bsmbIkT-OxtW5BmX12tmsaKn
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

!pip install hvplot
import hvplot
import hvplot.pandas

pd.options.plotting.backend = 'hvplot'

df = pd.read_csv("https://raw.githubusercontent.com/syamkakarla98/Dimensionality-reduction-and-classification-on-Hyperspectral-Images-Using-Python/master/Complete_Data_.csv")
df.head(3)

#processando os indices do dataframe
from sklearn.preprocessing import StandardScaler

ind=[]
for i in range(200):
    ind.append('px'+str(i+1))

#separando o que vai ser X (dados) e Y (classe)
features = ind
X = df.loc[:, features].values
# Separating out the target
Y = df.loc[:,['target']].values
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test, indices_train, indices_test  = train_test_split(X, Y,  range(X.shape[0]), 
                                                                                  test_size = 0.30, random_state = 11, stratify=Y)

svm = SVC(C = 3500, kernel = 'rbf', gamma='scale', cache_size = 16*1024)
svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(f'Accuracy: {accuracy_score(y_test, y_pred)*100}%')

!pip install -q scikit-plot

import scikitplot as skplt

skplt.metrics.plot_confusion_matrix(
    y_test, 
    y_pred,
    figsize=(12,12));

#!pip install plotly
import plotly.graph_objects as go

fig = go.Figure(data=go.Heatmap(
                   z= confusion_matrix(y_test, y_pred),
                   x=[f'target-{i}' for i in np.unique(df.loc[:, 'target'].values)],
                   y=[f'target-{i}' for i in np.unique(df.loc[:, 'target'].values)],
                   hoverongaps = False))
fig.show()

# print(confusion_matrix(y_test,y_pred))
print('Classification report:\n',classification_report(y_test,y_pred))

plt.figure(figsize=(8, 6))
plt.imshow(df.iloc[:, -1].values.reshape((145, 145)), cmap='jet')
plt.colorbar()
plt.axis('off')
plt.title('Ground Truth')
plt.savefig('ground_truth.png')
plt.show()

#!pip install tqdm
from tqdm import tqdm
pre = y_pred

clmap = [0]*X.shape[0]

for i in tqdm(range(len(indices_train))):
    clmap[indices_train[i]] = Y[indices_train[i]]

for i in tqdm(range(len(indices_test))):
    clmap[indices_test[i]] = pre[i]

plt.figure(figsize=(8, 6))
plt.imshow(np.array(clmap).reshape((145, 145)), cmap='jet')
plt.colorbar()
plt.axis('off')
plt.title('Classification Map (SVM)')
plt.savefig('Classification_map.png')
plt.show()