# -*- coding: utf-8 -*-
"""Manipulação de HSI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13HgdLRqb2mENp8OdeJfkFvKneHR0r46h

Leitura da HSI
"""

from scipy.io import loadmat

def read_HSI():
  X = loadmat('Indian_pines_corrected.mat')['indian_pines_corrected']
  y = loadmat('Indian_pines_gt.mat')['indian_pines_gt']
  print(f"X shape: {X.shape}\ny shape: {y.shape}")
  return X, y

X, y = read_HSI()

